### ISSUE TITLE
Argument 0 (<null>) of RCTUIManager.measure could not be processed.

### ISSUE THREAD

**Issue by Sh3rawi** [alinz/react-native-dropdown#10]
When implementing this component in my iOS app this error comes up.
I have done the same steps as in the example; the componentDidMount part as well as the _getOptionList. 
Using ReactNative 0.11.0.

**Comment by alinz** [comment]
@Sh3rawi, well I need to see the code, can you provide an example that doesn't work? Keep in mind, you need to call `updatePosition` for all the `Select` elements and `OptionList` components.  The function normalizes the position of these elements.

``` js
  componentDidMount() {
    updatePosition(this.refs['SELECT1']);
    updatePosition(this.refs['SELECT2']);

    updatePosition(this.refs['OPTIONLIST']);
  }
```

**Comment by Sh3rawi** [comment]
@alinz Sorry, my mistake. My eyes didn't catch the last OptionList component.

**Comment by UKDeveloper99** [comment]
Something tells me this happened because you were trying to access a ref that is null because you put the dropdown list in the renderScene function of a navigator. I had the exact same problem.

You have to change all the refs to this.refs.navigator.refs['SELECT1'] etc.

Don't forget to give the actual navigator a ref 
<Navigator
   ref='navigator'

@Sh3rawi
