### ISSUE TITLE
Dropdown not working in Android

### ISSUE THREAD

**Issue by HectorFL** [alinz/react-native-dropdown#24]
Hi, maybe I miss something, but isn't working in Android, not errors, simply not working.

Must I add edit some file that is not in the documentation? Thanks.

**Comment by walter211** [comment]
me too

**Comment by spinningideas** [comment]
me too

**Comment by adityamukeshthakur** [comment]
I do not understand. I appreciate the work you do for the community. But how can you claim that it supports Android when clearly there are a lot of bugs? I wasted one whole day trying figure out how to fix it and now I'm behind schedule.

**Comment by alinz** [comment]
I'm sorry to hear that. But you should know that any open source projects require constant work and time. I have been busy doing my day job. This is my small contribution back to community. So in order for me to support it I have to find free time. 

I will try to find some time to help you but please don't argue that because of my project, you are behind of your project. :( instead of bashing me/others, help me improve the project by providing pull requests.

**Comment by adityamukeshthakur** [comment]
I'm not bashing you. I do appreciate your efforts, but there are people who've been reporting issues for over a month. You don't have the time to even acknowledge their inputs. But as soon as someone puts across his issue aggressively, you reply in less than 24 hours. That speaks for itself. Atleast in the description you could mention that android support is not 100% bug free so that people would atleast be prepared to look for other alternatives.

**Comment by alinz** [comment]
@adityamukeshthakur I don't appreciate your comment. You have clearly no understanding how open source projects work. Open source project is a collaboration of so many people. I might be a owner of this project but once the project becomes open to everyone, everyone can fork it and make it their own. They can tweak it. I'm not responsible for anything that you do with your project. 

Usually when you see something, specially open source projects, you first create a prototype to see if it satisfy your requirement. If it's not try asking people. 

I try my best to help other and that's why @gs-akhan is helping me and others to push forward this project. 

If you don't like what you see, just spend your time and fix it and give us a pull request, fork it and create a brand new project.

and by the way, nothing is 100% bug free! This is your job as a developer to find an alternative not my job.

I'm sorry that instead of encourage you to fix the actual problem, you have started this type of communication and that is why I'm responding to you like this.

I'm closing this ticket because it has nothing to do with issue and open a new one.
