### ISSUE TITLE
Rendering order

### ISSUE THREAD

**Issue by krjw** [alinz/react-native-dropdown#27]
Your gif which shows the example renders the top Dropdown in front of the bottom one. As far as I know react native does not support z index and the render order depends on the order of the components in the render function. How did u manage to render the list over the bottom dropdown. I have found a package which apparently supports basic z index. I will try to use this until I find a better solution.

Greetings i7clock

**Comment by alinz** [comment]
@i7clock, well the concept is easy, react-native renders everything in order. So the last item has higher index. What I ended up was introducing 2 components. the first one is `Select` component which you define all options and `OptionList` which needs to be placed as the last item to be rendered. `OptionList` is just a place holder for `Select` component to render it's view. 

I will close this issue since it's jus a question. feel free to continue the discussion here. 

Thank

**Comment by krjw** [comment]
@alinz So if I embed 2 of the Dropdowns inside a scrollview and then other components underneath ... lets say a picker for example. The view of the dropdown will render under these components? What do you suggest in this case? leaving enough space for the dropdown would make the UI look ridiculous... Is it possible to put the components in a different order but position them in a different order?

How did u do it in your demo with 2 dropdowns?

Thanks!

**Comment by krjw** [comment]
Ok got it.. sry for not understanding the OptionList placeholder which can be just placed as the last rendered object...
Thanks a lot!! very useful package!!!

**Comment by alinz** [comment]
Don't be sorry, glad that you undrestand it. Let me know if you need more help!
