### ISSUE TITLE
How do I import the components in ES6 style?

### ISSUE THREAD

**Issue by brangnu** [alinz/react-native-dropdown#48]
I tried the following.

import {Select,  Option,  OptionList,  updatePosition} from 'react-native-dropdown';

I got the following error from React Native.

"Seems you're trying to access 'ReactNative.Component' from the 'react-native' package. Perhaps you meant to access 'React.Component' from the 'react' package instead?

For example, instead of:

  import React, { Component, View } from 'react-native';

You should now do:

  import React, { Component } from 'react';
  import { View } from 'react-native';"

If I delete the import line from 'react-native-dropdown', the App just works fine.

**Comment by nhuutri2** [comment]
Hi

How do you fix it?

Thanks

**Comment by yellowbang** [comment]
some problem. how to fix it?

**Comment by dsernst** [comment]
It looks like this issue is because of an incompatibility with newer versions of `react-native`.

Following the instructions from [this comment](https://github.com/alinz/react-native-dropdown/issues/44#issuecomment-234528214) to use [this updated version (PR pending)](https://github.com/alinz/react-native-dropdown/pull/41) made the issue go away for me:

```
Go to project folder
rm -rf node_modules/react-native-dropdown
npm install https://github.com/g6ling/react-native-dropdown --save
```

😎

**Comment by ShivangiAgrawal** [comment]
I am getting undefined is not an object with this as well
